-- Table Zoo.Site
INSERT INTO Zoo.Site VALUES( 1, 'Miskolci Állatkert', 212000.35, '9:00 - 17:00' );
INSERT INTO Zoo.Site VALUES( 2, 'Nyíregyházi Állatpark' , 300000.28, '9:00 - 17:00' );
INSERT INTO Zoo.Site VALUES( 3, 'Debreceni Állatkert és Vidámpark', 170000.00, '9:00 - 15:30' );
INSERT INTO Zoo.Site VALUES( 4, 'Kittenberg Kálmán Állatkert és Botanikus kert, Veszprém', 170500.65, '9:00 - 16:00' );
INSERT INTO Zoo.Site VALUES( 5, 'Fővárosi Állat- és Növénykert', 184000.53, '9:00 - 17:30' );

-- Table Zoo.Employee
INSERT INTO Zoo.Employee VALUES( 1, 'Kovács', 'János', '1979-11-02', 'M', 4 );
INSERT INTO Zoo.Employee VALUES( 2, 'Jakab', 'József', '1954-12-08', 'M', 1 );
INSERT INTO Zoo.Employee VALUES( 3, 'Menyhért', 'András', '2000-05-17', 'M', 2 );
INSERT INTO Zoo.Employee VALUES( 4, 'Kis', 'Renáta', '1999-10-10', 'F', 4 );
INSERT INTO Zoo.Employee VALUES( 5, 'Verőczei', 'Amália', '2001-12-03', 'F', 5 );
INSERT INTO Zoo.Employee VALUES( 6, 'Tóth', 'István', '1968-01-13', 'M', 1 );
INSERT INTO Zoo.Employee VALUES( 7, 'Kiss', 'Veronika', '1987-06-09', 'F', 3 );
INSERT INTO Zoo.Employee VALUES( 8, 'Magyar', 'Zsófia', '2001-02-28', 'F', 3 );
INSERT INTO Zoo.Employee VALUES( 9, 'Adorján', 'Zsolt', '1977-08-28', 'M', 2 );
INSERT INTO Zoo.Employee VALUES( 10, 'Mészáros', 'Attila', '1987-05-12', 'M', 3 );
INSERT INTO Zoo.Employee VALUES( 11, 'Vass', 'Zsombor', '1957-12-02', 'M', 1 );
INSERT INTO Zoo.Employee VALUES( 12, 'Hajdú', 'Patrícia', '1966-10-22', 'F', 5 );
INSERT INTO Zoo.Employee VALUES( 13, 'Balla', 'Zsombor', '1977-03-04', 'M', 3 );
INSERT INTO Zoo.Employee VALUES( 14, 'Sipos', 'István', '2002-09-10', 'M', 4 );
INSERT INTO Zoo.Employee VALUES( 15, 'Illés', 'Patrik', '1988-05-09', 'M', 5 );
INSERT INTO Zoo.Employee VALUES( 16, 'Horváth', 'Milla', '1969-03-14', 'F', 2 );
INSERT INTO Zoo.Employee VALUES( 17, 'Orbán', 'Kevin', '1999-07-13', 'M', 1 );
INSERT INTO Zoo.Employee VALUES( 18, 'László', 'Bence', '1987-12-30', 'M', 4 );
INSERT INTO Zoo.Employee VALUES( 19, 'Bogdán', 'Antal', '1965-05-03', 'M', 1 );
INSERT INTO Zoo.Employee VALUES( 20, 'Szűcs', 'Gábor', '1964-12-11', 'M', 5 );
INSERT INTO Zoo.Employee VALUES( 21, 'Balogh', 'Boglárka', '2000-11-04', 'F', 4 );
INSERT INTO Zoo.Employee VALUES( 22, 'Csonka', 'Klaudia', '1978-02-11', 'F', 3 );
INSERT INTO Zoo.Employee VALUES( 23, 'Balázs', 'Marianna', '2001-07-09', 'F', 4 );
INSERT INTO Zoo.Employee VALUES( 24, 'Faragó', 'Martina', '2003-11-13', 'F', 1 );
INSERT INTO Zoo.Employee VALUES( 25, 'Hegedűs', 'Flóra', '1996-01-16', 'F', 2 );
INSERT INTO Zoo.Employee VALUES( 26, 'Török', 'Izabella', '1978-05-22', 'F', 5 );
INSERT INTO Zoo.Employee VALUES( 27, 'Boros', 'Evelin', '2000-05-03', 'F', 3 );
INSERT INTO Zoo.Employee VALUES( 28, 'Bognár', 'Kornél', '1977-06-02', 'M', 2 );
INSERT INTO Zoo.Employee VALUES( 29, 'Kelemen', 'Klaudia', '2001-04-19', 'F', 2 );
INSERT INTO Zoo.Employee VALUES( 30, 'Dobos', 'Henriett', '1988-07-19', 'F', 5 );
INSERT INTO Zoo.Employee VALUES( 31, 'Váradi', 'Bence', '1998-11-07', 'M', 5 );
INSERT INTO Zoo.Employee VALUES( 32, 'Simon', 'Zoltán', '1969-12-08', 'M', 4 );
INSERT INTO Zoo.Employee VALUES( 33, 'Simon', 'Géza', '1972-03-17', 'M', 4 );
INSERT INTO Zoo.Employee VALUES( 34, 'Simon', 'Péter', '2000-10-10', 'M', 5 );
INSERT INTO Zoo.Employee VALUES( 35, 'Mészáros', 'Julianna', '1965-04-04', 'F', 3 );
INSERT INTO Zoo.Employee VALUES( 36, 'Török', 'Maja', '1978-04-15', 'F', 5 );
INSERT INTO Zoo.Employee VALUES( 37, 'Barna', 'Sándor', '1964-12-19', 'M', 3 );
INSERT INTO Zoo.Employee VALUES( 38, 'Péter', 'Patrik', '1985-01-28', 'M', 2 );
INSERT INTO Zoo.Employee VALUES( 39, 'Tamás', 'Dorottya', '1966-12-11', 'F', 3 );
INSERT INTO Zoo.Employee VALUES( 40, 'Pap', 'Aranka', '1953-04-11', 'F', 5 );
INSERT INTO Zoo.Employee VALUES( 41, 'László', 'Péter', '1968-12-17', 'M', 2 );
INSERT INTO Zoo.Employee VALUES( 42, 'Hegedűs', 'Boglárka', '1988-11-12', 'F', 3 );
INSERT INTO Zoo.Employee VALUES( 43, 'Szilágyi', 'Milán', '2003-02-15', 'M', 4 );
INSERT INTO Zoo.Employee VALUES( 44, 'Varga', 'Botond', '1977-06-13', 'M', 2 );
INSERT INTO Zoo.Employee VALUES( 45, 'Gáspár', 'Mária', '1959-09-17', 'F', 4 );
INSERT INTO Zoo.Employee VALUES( 46, 'Simon', 'Lívia', '1997-06-14', 'F', 5 );
INSERT INTO Zoo.Employee VALUES( 47, 'Gáspár', 'Bence', '1999-07-29', 'M', 1 );
INSERT INTO Zoo.Employee VALUES( 48, 'Farkas', 'Áron', '2002-02-28', 'M', 1 );
INSERT INTO Zoo.Employee VALUES( 49, 'Fábián', 'Evelin', '1985-03-19', 'F', 1 );
INSERT INTO Zoo.Employee VALUES( 50, 'Fodor', 'Kata', '1999-09-23', 'F', 1 );

-- Table Zoo.Employee_post
INSERT INTO Zoo.Employee_post VALUES( 1, 'Szemétszedő', 1 );
INSERT INTO Zoo.Employee_post VALUES( 2, 'Etető', 2 );
INSERT INTO Zoo.Employee_post VALUES( 3, 'Kisállat gondozó', 3 );
INSERT INTO Zoo.Employee_post VALUES( 4, 'Terrárium takarító', 4 );
INSERT INTO Zoo.Employee_post VALUES( 5, 'Pénztáros', 5 );
INSERT INTO Zoo.Employee_post VALUES( 6, 'Jegyszedő', 6 );
INSERT INTO Zoo.Employee_post VALUES( 7, 'Karbantartó', 7 );
INSERT INTO Zoo.Employee_post VALUES( 8, 'Kisvasút vezető', 8 );
INSERT INTO Zoo.Employee_post VALUES( 9, 'Gondnok', 9 );
INSERT INTO Zoo.Employee_post VALUES( 10, 'Kalandpark igazgató', 10 );
INSERT INTO Zoo.Employee_post VALUES( 11, 'Etető', 11 );
INSERT INTO Zoo.Employee_post VALUES( 12, 'Jegyszedő', 12 );
INSERT INTO Zoo.Employee_post VALUES( 13, 'Terrárium takarító', 13 );
INSERT INTO Zoo.Employee_post VALUES( 14, 'Jegyszedő', 14 );
INSERT INTO Zoo.Employee_post VALUES( 15, 'Kisvasút vezető', 15 );
INSERT INTO Zoo.Employee_post VALUES( 16, 'Gondnok', 16 );
INSERT INTO Zoo.Employee_post VALUES( 17, 'Szemétszedő', 17 );
INSERT INTO Zoo.Employee_post VALUES( 18, 'Szemétszedő', 18 );
INSERT INTO Zoo.Employee_post VALUES( 19, 'Jegyszedő', 19 );
INSERT INTO Zoo.Employee_post VALUES( 20, 'Karbantartó', 20 );
INSERT INTO Zoo.Employee_post VALUES( 21, 'Kisállat gondozó', 21 );
INSERT INTO Zoo.Employee_post VALUES( 22, 'Etető', 22 );
INSERT INTO Zoo.Employee_post VALUES( 23, 'Etető', 23 );
INSERT INTO Zoo.Employee_post VALUES( 24, 'Állatorvos', 23 );
INSERT INTO Zoo.Employee_post VALUES( 25, 'Gondozó', 24 );
INSERT INTO Zoo.Employee_post VALUES( 26, 'Zoo pedagógus', 25 );
INSERT INTO Zoo.Employee_post VALUES( 27, 'Gondozó', 26 );
INSERT INTO Zoo.Employee_post VALUES( 28, 'Gondozó', 27 );
INSERT INTO Zoo.Employee_post VALUES( 29, 'Gondnok', 28 );
INSERT INTO Zoo.Employee_post VALUES( 30, 'Jegyszedő', 29 );
INSERT INTO Zoo.Employee_post VALUES( 31, 'Pénztáros', 30 );
INSERT INTO Zoo.Employee_post VALUES( 32, 'Terrárium takarító', 31 );
INSERT INTO Zoo.Employee_post VALUES( 33, 'Zoo pedagógus', 32 );
INSERT INTO Zoo.Employee_post VALUES( 34, 'Gondozó', 32 );
INSERT INTO Zoo.Employee_post VALUES( 35, 'Szemétszedő', 33 );
INSERT INTO Zoo.Employee_post VALUES( 36, 'Kisvasút vezető', 34 );
INSERT INTO Zoo.Employee_post VALUES( 37, 'Karbantartó', 35 );
INSERT INTO Zoo.Employee_post VALUES( 38, 'Zoo pedagógus', 36 );
INSERT INTO Zoo.Employee_post VALUES( 39, 'Gondozó', 37 );
INSERT INTO Zoo.Employee_post VALUES( 40, 'Szemétszedő', 38 );
INSERT INTO Zoo.Employee_post VALUES( 41, 'Etető', 39 );
INSERT INTO Zoo.Employee_post VALUES( 42, 'Jegyszedő', 40 );
INSERT INTO Zoo.Employee_post VALUES( 43, 'Gondnok', 41 );
INSERT INTO Zoo.Employee_post VALUES( 44, 'Jegyszedő', 42 );
INSERT INTO Zoo.Employee_post VALUES( 45, 'Pénztáros', 43 );
INSERT INTO Zoo.Employee_post VALUES( 46, 'Terrárium takarító', 44 );
INSERT INTO Zoo.Employee_post VALUES( 47, 'Zoo pedagógus', 45 );
INSERT INTO Zoo.Employee_post VALUES( 48, 'Kalandpark igazgató', 46 );
INSERT INTO Zoo.Employee_post VALUES( 49, 'Etető', 47 );
INSERT INTO Zoo.Employee_post VALUES( 50, 'Jegyszedő', 48 );
INSERT INTO Zoo.Employee_post VALUES( 51, 'Terrárium takarító', 49 );
INSERT INTO Zoo.Employee_post VALUES( 52, 'Gondozó', 50 );

-- Table Zoo.Habitat
INSERT INTO Zoo.Habitat VALUES( 1, 'Medve park', '#3', 'Az állatkerti medvék élőhelye. Jelenleg három medve található itt, Jázmin, Andor és Matykó. Szeretik a látogatókat, mindig érdeklődve nézelődnek.', 3, 5 );
INSERT INTO Zoo.Habitat VALUES( 2, 'Fóka show', '#2', 'Az állatparki fóka show ezen a helyen kerül megrendezésre a nyitást követő minden fél órában. A kis- és nagycsaládosok kedvenc időtöltése a vadasparkban, kicsik és nagyon egyaránt szeretik.', 2, 2 );
INSERT INTO Zoo.Habitat VALUES( 3, 'Elefánt lak', '#15', 'Az afrikai elefántjaink élőhelye. Trópus a mérsékelt éghajlaton. Csacsi és Béci a két kan elefánt egymás testvérei. Szeretik a túristákat, ha tehetnék szívesen közéjük is merészkednének. Barátságos állatok.', 4, 5 );
INSERT INTO Zoo.Habitat VALUES( 4, 'Macik ketrce', '#4', 'Borka és Dorka, állatkertünk két büszke mackója. Szeretik a látogatókat. Gabi maci, az egykori állatkerti medve emlékét őrzi a két kislány, akik nap mint nap játékosan töltik az időt.', 2, 1 );
INSERT INTO Zoo.Habitat VALUES( 5, 'Muflonok dombja', '#22', 'Vadasparkunk muflonjai itt találhatóak. Barátságosak, túrista kedvelők, szeretik a finom falatokat.', 3, 4 );
INSERT INTO Zoo.Habitat VALUES( 6, 'Oroszlánok szavannája', '#15', 'Morci és Bamba ikertestvérek. A kan oroszlánok állandó civakodása, játéka mindig mosolyt csal a látogatók arcára, különösképp a gyermekekére. Aranyos, kedves állatok, akik szeretik a finom falatokat.', 2, 3 );
INSERT INTO Zoo.Habitat VALUES( 7, 'Kisállatok tavernája', '#1', 'Misi a mosómedve és barátja, Janka, a cirmos vadcica nagyon jól eléldegélnek egymás mellett. Kvázi szomszédok. Állatkertünk dolgozói ezért is döntöttek úgy, hogy egy placcra rakják őket, hiszen oly jóban vannak.', 2, 5 );
INSERT INTO Zoo.Habitat VALUES( 8, 'Majmócák ketrece', '#16', 'Viki és Sanyi állatkertünk büszke páviánjai. Szeretik a látogatóak, csak úgy, mint a napi eleségüket. Ha pedig kedvük van, akár önök is etethetik őket egy pár száz forint ellenében. Azt szeretik csak igazán.', 3, 1 );
INSERT INTO Zoo.Habitat VALUES( 9, 'Szurikáták szigete', '#18', 'Ki ne imádná a kis érdeklődő szurikátákat. Nálunk rögtön 4-et is örökbe fogadhat, vagy csak látogathat is.', 10, 4 );
INSERT INTO Zoo.Habitat VALUES( 10, 'Baromfi udvar', '#30', 'Állatkertünk baromfi udvarában a hétköznapi házi baromfitól a páván át a gyöngytyúkig mindenféle állat megtalálható. Simogatni ugyan nem, de etetni bátran lehet őket, na persze csak felelősséggel.', 15, 4 );
INSERT INTO Zoo.Habitat VALUES( 11, 'Zsiráfok ketrece', '#14', 'Lurkó és Törpe, a két zsiráf nagyon élvezi az életet még a ketrecen belül is. Gondozóink egy saját szavannai kifutót állíttotak nekik össze, amit nagyon élveznek használni. Imádják, ha a látogatók megcsodálják őket.', 2, 2 );
INSERT INTO Zoo.Habitat VALUES( 12, 'Kecskék kuckója', '#34', 'Kecskesimogatás? Nálunk az is megvalósulhat. Ha gyermeke arra vágyik, hogy egy pár óráig az állatok közelében legyen, akkor itt a helye.', 4, 1 );
INSERT INTO Zoo.Habitat VALUES( 13, 'Oposszumok kukcója', '#13', 'Kis szürke barátaink nagyon élvezik az állatkerti létet. Mici, az oposszumbébi, az első pillanatban örökbefogadóra talált. Simogatni és etetni ugyan nem, de nézni, ahogy egymással játszanak lehet. Édesek és szeretik a látogatókat.', 5, 1 );
INSERT INTO Zoo.Habitat VALUES( 14, 'Tigris lak', '#10', 'Marci a 10 éves bengáli tigris korához képest nagyon jól tartja magát. Szereti a látogatókat, főleg a gondozóját és az örökbefogadóját.', 2, 3 );

-- Table Zoo.User
INSERT INTO Zoo.User VALUES( 1, 'Allatbarat', 'allat123', 'M', 'Kiss', 'Sándor', '8200', 'Veszprém', 'Petőfi Sándor utca', 3 );
INSERT INTO Zoo.User VALUES( 2, 'KisAllatokért', 'allatbaratvagyok', 'F', 'Megyeri', 'Flóra', '1106', 'Budapest', 'Rákosvölgyi utca', 27 );
INSERT INTO Zoo.User VALUES( 3, 'Vadoc', 'fegyo02', 'M', 'Fegyver', 'Sándor', '4024', 'Debrecen', 'Kossuth utca', 26 );
INSERT INTO Zoo.User VALUES( 4, 'SzurikatakKedvence', 'szuri123', 'M', 'Hajnal', 'Sándor', '8200', 'Veszprém', 'Adám István utca', 15 );
INSERT INTO Zoo.User VALUES( 5, 'OroszlánMama', 'mamaoroszlan', 'F', 'Kis', 'Mária', '4002', 'Debrecen', 'Gombvirág utca', 12 );
INSERT INTO Zoo.User VALUES( 6, 'MaciNagyi', 'macinagyi', 'F', 'Sándorné Arany', 'Virág', '3525', 'Miskolc', 'Estike utca', 10 );
INSERT INTO Zoo.User VALUES( 7, 'VikiPapa', 'vikipapa', 'M', 'Andor', 'Ferenc', '3525', 'Miskolc', 'Mohostó utca', 15 );
INSERT INTO Zoo.User VALUES( 8, 'Posmluvr', 'possumlover', 'F', 'Kazai', 'Eszter', '3521', 'Miskolc', 'Új élet utca', 24 );
INSERT INTO Zoo.User VALUES( 9, 'MosóMisi', 'misimoso', 'M', 'Virág', 'György', '1181', 'Budapest', 'Klapka György utca', 4 );
INSERT INTO Zoo.User VALUES( 10, 'FókaMan', 'fokaman25', 'M', 'Károly', 'Mihály', '4405', 'Nyíregyháza', 'Nárcisz utca', 73 );
INSERT INTO Zoo.User VALUES( 11, 'CicaLover', 'cicalover123', 'F', 'Macskás', 'Márta', '1102', 'Budapest', 'Baross utca', 5 );

-- Table Zoo.Animal
INSERT INTO Zoo.Animal VALUES( 1, 'Mici', 'Oposszum', 'Az állatkert egyetlen oposszumbébije', 13, 8 );
INSERT INTO Zoo.Animal VALUES( 2, 'Borka', 'Medve', 'Az állatkert egyik nőstény medvéje', 4, 6 );
INSERT INTO Zoo.Animal VALUES( 3, 'Dorka', 'Medve', 'Az állatkert egyik nőstény medvéje', 4, NULL );
INSERT INTO Zoo.Animal VALUES( 4, 'Jázmin', 'Medve', 'Az állatkert nőstény medvéje', 1, NULL );
INSERT INTO Zoo.Animal VALUES( 5, 'Andor', 'Medve', 'Az állatkert egyik kan medvéje', 1, NULL );
INSERT INTO Zoo.Animal VALUES( 6, 'Matykó', 'Medve', 'Az állatkert egyik kan medvéje', 1, NULL );
INSERT INTO Zoo.Animal VALUES( 7, 'Csacsi', 'Elefánt', 'Az állatkert egyik elefántja', 3, NULL );
INSERT INTO Zoo.Animal VALUES( 8, 'Béci', 'Elefánt', 'Az állatkert egyik elefántja', 3, NULL );
INSERT INTO Zoo.Animal VALUES( 9, 'Morci', 'Oroszlán', 'Az állatkert egyik oroszlánja', 6, 5 );
INSERT INTO Zoo.Animal VALUES( 10, 'Bamba', 'Oroszlán', 'Az állatkert egyik oroszlánja', 6, NULL );
INSERT INTO Zoo.Animal VALUES( 11, 'Misi', 'Mosómedve', 'Az állatkert egyetlen mosómedvéje', 7, 9 );
INSERT INTO Zoo.Animal VALUES( 12, 'Janka', 'Vadmacska', 'Az állatkert egyetlen vadmacskája', 7, 11 );
INSERT INTO Zoo.Animal VALUES( 13, 'Viki', 'Pávián', 'Az állatkert nőstény páviánja', 8, 7 );
INSERT INTO Zoo.Animal VALUES( 14, 'Sanyi', 'Pávián', 'Az állatkert kan páviánja', 8, NULL );
INSERT INTO Zoo.Animal VALUES( 15, 'Lurkó', 'Zsiráf', 'Az állatkert egyik zsiráfja', 11, NULL );
INSERT INTO Zoo.Animal VALUES( 16, 'Törpe', 'Zsiráf', 'Az állatkert egyik zsiráfja', 11, NULL );
INSERT INTO Zoo.Animal VALUES( 17, 'Lóci', 'Fóka', 'Az állatpark egyik fóka kanja', 2, 10 );
INSERT INTO Zoo.Animal VALUES( 18, 'Móci', 'Fóka', 'Az állatpark egyik fóka kanja', 2, NULL );
INSERT INTO Zoo.Animal VALUES( 19, 'Hegyes', 'Muflon', 'Az állatkert kan muflonja', 5, NULL );
INSERT INTO Zoo.Animal VALUES( 20, 'Kis Hegyes', 'Muflon', 'Az állatkert nőstény muflonja', 5, NULL );
INSERT INTO Zoo.Animal VALUES( 21, 'Figyelő', 'Szurikáta', 'Az állatkert legidősebb szurikátája', 9, 4 );
INSERT INTO Zoo.Animal VALUES( 22, 'Mókás', 'Szurikáta', 'Az állatkert legfiatalabb szurikátája', 9, NULL );
INSERT INTO Zoo.Animal VALUES( 23, 'Tollas', 'Gyöngytyúk', 'Az állatkert egyetlen gyöngytyúkja', 10, 1 );
INSERT INTO Zoo.Animal VALUES( 24, 'Szépséges', 'Páva', 'Az állatkert egyetlen pávája', 10, NULL );
INSERT INTO Zoo.Animal VALUES( 25, 'Szurkos', 'Szuritáka', 'Az állatkert egyik fiatal szurikátája', 9, NULL );
INSERT INTO Zoo.Animal VALUES( 26, 'Bébi', 'Szurikáta', 'Az állatkert egyik idősebb szurikátája', 9, 2 );
INSERT INTO Zoo.Animal VALUES( 27, 'Marci', 'Bengáli tigris', 'Az állatkert egyetlen bengáli tigrise', 14, 3 );
INSERT INTO Zoo.Animal VALUES( 28, 'Kis Bak', 'Kecske', 'Az állatkert egy fiatal kecskéje', 12, NULL );
INSERT INTO Zoo.Animal VALUES( 29, 'Nagy Bak', 'Kecske', 'Az állatkert egy idősebb kecskéje', 12, NULL );
INSERT INTO Zoo.Animal VALUES( 30, 'Józsi', 'Házi baromfi', 'Az állatkert házi baromfija', 10, NULL );

-- Table Zoo.Food
INSERT INTO Zoo.Food VALUES( 1, 'Fagyasztott nyershús', false );
INSERT INTO Zoo.Food VALUES( 2, 'Sárgarépa', true );
INSERT INTO Zoo.Food VALUES( 3, 'Spenót', false );
INSERT INTO Zoo.Food VALUES( 4, 'Sertés borda', true );
INSERT INTO Zoo.Food VALUES( 5, 'Aszalt gyümölcsök', true );
INSERT INTO Zoo.Food VALUES( 6, 'Sült husi', true );
INSERT INTO Zoo.Food VALUES( 7, 'Fagyasztott hering', true );

-- Table Zoo.Food_company
INSERT INTO Zoo.Food_company VALUES( 1, 'Állati zöldség/gyümölcs', 2 );
INSERT INTO Zoo.Food_company VALUES( 2, 'Állati zöldség/gyümölcs', 3 );
INSERT INTO Zoo.Food_company VALUES( 3, 'Állati zöldség/gyümölcs', 5 );
INSERT INTO Zoo.Food_company VALUES( 4, 'Felix állati eledel', 4 );
INSERT INTO Zoo.Food_company VALUES( 5, 'Felix állati eledel', 6 );
INSERT INTO Zoo.Food_company VALUES( 6, 'Frosty food', 1 );
INSERT INTO Zoo.Food_company VALUES( 7, 'Frosty food', 7 );

-- Table Zoo.Eat
INSERT INTO Zoo.Eat VALUES( 1, 1, '07:00, 18:00' );
INSERT INTO Zoo.Eat VALUES( 2, 4, '05:00, 12:00, 19:00' );
INSERT INTO Zoo.Eat VALUES( 3, 4, '05:00, 12:00, 19:00' );
INSERT INTO Zoo.Eat VALUES( 4, 6, '09:00, 13:00, 20:00' );
INSERT INTO Zoo.Eat VALUES( 5, 6, '09:00, 13:00, 20:00' );
INSERT INTO Zoo.Eat VALUES( 6, 6, '09:00, 13:00, 20:00' );
INSERT INTO Zoo.Eat VALUES( 7, 2, '05:00, 12:00, 19:00' );
INSERT INTO Zoo.Eat VALUES( 8, 3, '05:00, 12:00, 19:00' );
INSERT INTO Zoo.Eat VALUES( 9, 4, '05:00, 13:00, 20:00' );
INSERT INTO Zoo.Eat VALUES( 10, 4, '05:00, 13:00, 20:00' );
INSERT INTO Zoo.Eat VALUES( 11, 5, '09:00, 18:00' );
INSERT INTO Zoo.Eat VALUES( 12, 1, '07:00, 20:00' );
INSERT INTO Zoo.Eat VALUES( 13, 5, '06:00, 14:00, 20:00' );
INSERT INTO Zoo.Eat VALUES( 14, 5, '06:00, 14:00, 20:00' );
INSERT INTO Zoo.Eat VALUES( 15, 2, '07:00, 12:00, 18:00' );
INSERT INTO Zoo.Eat VALUES( 16, 2, '07:00, 12:00, 18:00' );
INSERT INTO Zoo.Eat VALUES( 17, 7, '07:00, 12:00, 18:00' );
INSERT INTO Zoo.Eat VALUES( 18, 7, '07:00, 12:00, 18:00' );
INSERT INTO Zoo.Eat VALUES( 19, 3, '05:00, 12:00, 17:00' );
INSERT INTO Zoo.Eat VALUES( 20, 5, '05:00, 12:00, 17:00' );
INSERT INTO Zoo.Eat VALUES( 21, 1, '07:00, 19:00' );
INSERT INTO Zoo.Eat VALUES( 22, 6, '08:00, 13:00, 20:00' );
INSERT INTO Zoo.Eat VALUES( 23, 2, '05:00, 20:00' );
INSERT INTO Zoo.Eat VALUES( 24, 3, '05:00, 20:00' );
INSERT INTO Zoo.Eat VALUES( 25, 6, '08:00, 13:00, 20:00' );
INSERT INTO Zoo.Eat VALUES( 26, 1, '08:00, 13:00, 20:00' );
INSERT INTO Zoo.Eat VALUES( 27, 4, '05:00, 12:00, 18:00' );
INSERT INTO Zoo.Eat VALUES( 28, 2, '07:00, 12:00, 18:00' );
INSERT INTO Zoo.Eat VALUES( 29, 3, '07:00, 12:00, 18:00' );
INSERT INTO Zoo.Eat VALUES( 30, 2, '05:00, 20:00' );